CREATE DATABASE test;
use test;
CREATE TABLE btest (aid INTEGER, aname STRING, salary DOUBLE);
INSERT INTO btest VALUES (101, Alex, 2137);
INSERT INTO btest VALUES (102, John, 4214);
INSERT INTO btest VALUES (103, Tom, 4577);
INSERT INTO btest VALUES (104, Marry, 4234);
INSERT INTO btest VALUES (105, Matthew, 8235);
INSERT INTO btest VALUES (106, Jimmy, 3245);
INSERT INTO btest VALUES (107, Robert, 4233);
INSERT INTO btest VALUES (108, Nuno, 1222);
INSERT INTO btest VALUES (109, Liam, 7566);
INSERT INTO btest VALUES (110, Noel, 9555);
INSERT INTO btest VALUES (111, Ted, 5987);
INSERT INTO btest VALUES (112, Barney, 5566);
SELECT * FROM btest;
SELECT * FROM btest WHERE aid = 110;
SELECT * FROM btest WHERE aid < 110;
SELECT * FROM btest WHERE aid > 105;
SELECT * FROM btest WHERE salary < 5000;
SELECT * From btest WHERE aname = Nuno;
SELECT aid FROM btest;
SELECT aname, salary FROM btest;
UPDATE btest SET salary = 70 WHERE aid = 112;
UPDATE btest SET salary = 7777;
SELECT * FROM btest WHERE aid = 110 AND salary = 7777;
CREATE TABLE BirthdayAndDepartment (birthday INTEGER, dept STRING);
INSERT INTO BirthdayAndDepartment VALUES (900914, MANAGEMENT);
INSERT INTO BirthdayAndDepartment VALUES (900907, NONE);
INSERT INTO BirthdayAndDepartment VALUES (910603, STUDENT);
SELECT * FROM BirthdayAndDepartment;
SELECT * FROM btest, BirthdayAndDepartment;
SELECT * FROM btest, BirthdayAndDepartment WHERE aid = 111;
SELECT * FROM btest, BirthdayAndDepartment WHERE aid = 111 AND birthday = 900914;