/* Generated By:JavaCC: Do not edit this line. SelectConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SelectConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENDOFSTATEMENT = 5;
  /** RegularExpression Id. */
  int STAR = 6;
  /** RegularExpression Id. */
  int EQUAL = 7;
  /** RegularExpression Id. */
  int POINT = 8;
  /** RegularExpression Id. */
  int OBRA = 9;
  /** RegularExpression Id. */
  int CBRA = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int SELECT = 12;
  /** RegularExpression Id. */
  int FROM = 13;
  /** RegularExpression Id. */
  int WHERE = 14;
  /** RegularExpression Id. */
  int CREATE = 15;
  /** RegularExpression Id. */
  int DATABASE = 16;
  /** RegularExpression Id. */
  int TABLE = 17;
  /** RegularExpression Id. */
  int USE = 18;
  /** RegularExpression Id. */
  int SHOW = 19;
  /** RegularExpression Id. */
  int DATABASES = 20;
  /** RegularExpression Id. */
  int INSERT = 21;
  /** RegularExpression Id. */
  int INTO = 22;
  /** RegularExpression Id. */
  int VALUES = 23;
  /** RegularExpression Id. */
  int UPDATE = 24;
  /** RegularExpression Id. */
  int SET = 25;
  /** RegularExpression Id. */
  int EXIT = 26;
  /** RegularExpression Id. */
  int CHAR = 27;
  /** RegularExpression Id. */
  int NUMCHAR = 28;
  /** RegularExpression Id. */
  int DIGIT = 29;
  /** RegularExpression Id. */
  int ATTR = 30;
  /** RegularExpression Id. */
  int VALUE = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\";\"",
    "\"*\"",
    "\"=\"",
    "\".\"",
    "<OBRA>",
    "<CBRA>",
    "\",\"",
    "<SELECT>",
    "<FROM>",
    "<WHERE>",
    "<CREATE>",
    "<DATABASE>",
    "<TABLE>",
    "<USE>",
    "<SHOW>",
    "<DATABASES>",
    "<INSERT>",
    "<INTO>",
    "<VALUES>",
    "<UPDATE>",
    "<SET>",
    "<EXIT>",
    "<CHAR>",
    "<NUMCHAR>",
    "<DIGIT>",
    "<ATTR>",
    "<VALUE>",
    "<NUMBER>",
  };

}
